package emit

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"github.com/mochilang/mochi-python/typemap"
	"github.com/mochilang/mochi-python/wrapper"
)

// Shim is the Mochi-side artefact emitted for one consumed PyPI package.
type Shim struct {
	// Package is the source PyPI distribution name (e.g. "httpx").
	Package string
	// Module is the shim module basename (`<Package>_shim`). The full file
	// path is `<Module>.mochi`.
	Module string
	// Source is the rendered Mochi source.
	Source string
	// SHA256 is the lowercase hex SHA-256 of Source. It is the
	// `wrapper-sha256` value the mochi.lock `[[python-package]]` entry
	// records (see MEP-71 §5 "Lockfile entry").
	SHA256 string
	// Decls lists every declaration the shim exposes, in emitted order.
	Decls []Decl
}

// DeclKind classifies a shim declaration. The set mirrors wrapper.ItemKind
// but resolves records vs. opaque types based on whether the type carries a
// structural body (records have Fields; interfaces and field-less records
// surface as opaque externs).
type DeclKind int

const (
	// DeclExternFun is `extern python fun name(P1, P2): R`.
	DeclExternFun DeclKind = iota
	// DeclTypeAlias is `type Name = { field: type, ... }` (Mochi record alias).
	DeclTypeAlias
	// DeclExternType is `extern python type Name` (opaque Mochi type).
	DeclExternType
	// DeclExternVar is `extern python var NAME: type`.
	DeclExternVar
)

func (k DeclKind) String() string {
	switch k {
	case DeclExternFun:
		return "extern_fun"
	case DeclTypeAlias:
		return "type_alias"
	case DeclExternType:
		return "extern_type"
	case DeclExternVar:
		return "extern_var"
	default:
		return "unknown"
	}
}

// Decl is one declaration in the shim.
type Decl struct {
	Kind     DeclKind
	Name     string         // declared name on the Mochi side
	Type     typemap.MochiType // associated type (fun signature, record, scalar)
	Source   string         // rendered line(s) in the shim
}

// Options configures the emit pass.
type Options struct {
	// Header controls whether the generated source begins with the
	// auto-generated banner comment. Default true.
	Header bool
	// IncludeSkipReport, when true, emits a trailing `// SKIPPED:` comment
	// block listing the Wrapper.Skipped entries. Default true.
	IncludeSkipReport bool
	// Generator overrides the generator identifier in the banner. Default
	// "mochi pkg lock".
	Generator string
}

// DefaultOptions returns the Options the bridge uses when the caller does
// not specialise. Header on, skip report on, generator "mochi pkg lock".
func DefaultOptions() Options {
	return Options{
		Header:            true,
		IncludeSkipReport: true,
		Generator:         "mochi pkg lock",
	}
}

// EmitShim renders the Mochi shim for the given wrapper. The output is
// deterministic for a given Wrapper + Options pair; the SHA-256 is
// computed over the rendered Source.
func EmitShim(w *wrapper.Wrapper, opts Options) (*Shim, error) {
	if w == nil {
		return nil, fmt.Errorf("emit: wrapper is nil")
	}
	if w.Package == "" {
		return nil, fmt.Errorf("emit: wrapper package is empty")
	}
	if opts.Generator == "" {
		opts.Generator = "mochi pkg lock"
	}
	s := &Shim{
		Package: w.Package,
		Module:  w.Package + "_shim",
	}
	var b strings.Builder
	if opts.Header {
		writeHeader(&b, w, opts)
	}
	items := append([]wrapper.Item(nil), w.Items...)
	sort.SliceStable(items, func(i, j int) bool {
		return items[i].SourceName < items[j].SourceName
	})
	// Group: type aliases, opaque externs, constants, functions. Within each
	// group, items remain in SourceName order.
	for _, group := range []wrapper.ItemKind{wrapper.ItemRecord, wrapper.ItemInterface, wrapper.ItemConstant, wrapper.ItemFunc} {
		for _, it := range items {
			if it.Kind != group {
				continue
			}
			d := renderItem(it)
			if d == nil {
				continue
			}
			b.WriteString(d.Source)
			if !strings.HasSuffix(d.Source, "\n") {
				b.WriteString("\n")
			}
			s.Decls = append(s.Decls, *d)
		}
		if hasItem(items, group) {
			b.WriteString("\n")
		}
	}
	if opts.IncludeSkipReport {
		writeSkipReport(&b, w)
	}
	s.Source = b.String()
	sum := sha256.Sum256([]byte(s.Source))
	s.SHA256 = hex.EncodeToString(sum[:])
	return s, nil
}

func hasItem(items []wrapper.Item, kind wrapper.ItemKind) bool {
	for _, it := range items {
		if it.Kind == kind {
			return true
		}
	}
	return false
}

func writeHeader(b *strings.Builder, w *wrapper.Wrapper, opts Options) {
	fmt.Fprintf(b, "// Auto-generated by %s — do not edit.\n", opts.Generator)
	fmt.Fprintf(b, "// MEP-71 Mochi shim for source package: %s\n", w.Package)
	fmt.Fprintf(b, "// Items: %d  Skipped: %d  Loop: %s\n", len(w.Items), len(w.Skipped), w.Loop)
	b.WriteString("\n")
}

func writeSkipReport(b *strings.Builder, w *wrapper.Wrapper) {
	if len(w.Skipped) == 0 {
		return
	}
	b.WriteString("// SKIPPED items (see SKIPPED.txt for full report):\n")
	for _, s := range w.Skipped {
		fmt.Fprintf(b, "//   %s (%s)\n", s.ItemPath, s.Reason)
	}
}

func renderItem(it wrapper.Item) *Decl {
	switch it.Kind {
	case wrapper.ItemFunc:
		return renderFun(it)
	case wrapper.ItemRecord:
		return renderRecord(it)
	case wrapper.ItemInterface:
		return renderInterface(it)
	case wrapper.ItemConstant:
		return renderConstant(it)
	}
	return nil
}

func renderFun(it wrapper.Item) *Decl {
	if it.Type.Kind != typemap.KindFun {
		return nil
	}
	params := it.Type.FunParams()
	ret := it.Type.Return()
	var parts []string
	for _, p := range params {
		parts = append(parts, p.Render())
	}
	line := fmt.Sprintf("extern python fun %s(%s): %s",
		it.Name, strings.Join(parts, ", "), ret.Render())
	return &Decl{
		Kind:   DeclExternFun,
		Name:   it.Name,
		Type:   it.Type,
		Source: line,
	}
}

func renderRecord(it wrapper.Item) *Decl {
	if it.Type.Kind != typemap.KindRecord || len(it.Type.Fields) == 0 {
		// Field-less record surfaces as opaque extern type.
		return &Decl{
			Kind:   DeclExternType,
			Name:   it.Name,
			Type:   it.Type,
			Source: fmt.Sprintf("extern python type %s", it.Name),
		}
	}
	names := make([]string, 0, len(it.Type.Fields))
	idx := make(map[string]typemap.MochiField, len(it.Type.Fields))
	for _, f := range it.Type.Fields {
		names = append(names, f.Name)
		idx[f.Name] = f
	}
	sort.Strings(names)
	var b strings.Builder
	fmt.Fprintf(&b, "type %s = {\n", it.Name)
	for i, n := range names {
		f := idx[n]
		sep := ","
		if i == len(names)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "  %s: %s%s\n", n, f.Type.Render(), sep)
	}
	b.WriteString("}\n")
	return &Decl{
		Kind:   DeclTypeAlias,
		Name:   it.Name,
		Type:   it.Type,
		Source: b.String(),
	}
}

func renderInterface(it wrapper.Item) *Decl {
	// Mochi grammar currently models Protocols as opaque extern types; the
	// wrapper handles dispatch and structural conformance is enforced by the
	// .pyi alongside.
	return &Decl{
		Kind:   DeclExternType,
		Name:   it.Name,
		Type:   it.Type,
		Source: fmt.Sprintf("extern python type %s", it.Name),
	}
}

func renderConstant(it wrapper.Item) *Decl {
	return &Decl{
		Kind:   DeclExternVar,
		Name:   it.Name,
		Type:   it.Type,
		Source: fmt.Sprintf("extern python var %s: %s", it.Name, it.Type.Render()),
	}
}
