package emit

import (
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/mochilang/mochi-python/errors"
	"github.com/mochilang/mochi-python/typemap"
	"github.com/mochilang/mochi-python/wrapper"
)

func TestEmitShimRequiresWrapper(t *testing.T) {
	if _, err := EmitShim(nil, DefaultOptions()); err == nil {
		t.Fatal("expected error for nil wrapper")
	}
}

func TestEmitShimRequiresPackageName(t *testing.T) {
	if _, err := EmitShim(&wrapper.Wrapper{}, DefaultOptions()); err == nil {
		t.Fatal("expected error for empty package")
	}
}

func TestEmitShimMetadata(t *testing.T) {
	w := &wrapper.Wrapper{Package: "httpx", Module: "httpx_externs"}
	s, err := EmitShim(w, DefaultOptions())
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if s.Package != "httpx" || s.Module != "httpx_shim" {
		t.Errorf("metadata: %+v", s)
	}
	if s.SHA256 == "" {
		t.Error("SHA256 missing")
	}
	sum := sha256.Sum256([]byte(s.Source))
	if hex.EncodeToString(sum[:]) != s.SHA256 {
		t.Errorf("SHA256 does not match Source")
	}
}

func TestEmitShimHeader(t *testing.T) {
	w := &wrapper.Wrapper{Package: "httpx"}
	s, _ := EmitShim(w, DefaultOptions())
	for _, head := range []string{
		"// Auto-generated by mochi pkg lock",
		"// MEP-71 Mochi shim for source package: httpx",
		"// Items: 0  Skipped: 0  Loop: per-call",
	} {
		if !strings.Contains(s.Source, head) {
			t.Errorf("missing header %q\n--- got ---\n%s", head, s.Source)
		}
	}
}

func TestEmitShimHeaderOff(t *testing.T) {
	w := &wrapper.Wrapper{Package: "httpx"}
	opts := DefaultOptions()
	opts.Header = false
	s, _ := EmitShim(w, opts)
	if strings.Contains(s.Source, "Auto-generated") {
		t.Errorf("Header should be suppressed: %s", s.Source)
	}
}

func TestEmitShimGeneratorOverride(t *testing.T) {
	w := &wrapper.Wrapper{Package: "httpx"}
	opts := DefaultOptions()
	opts.Generator = "test-runner"
	s, _ := EmitShim(w, opts)
	if !strings.Contains(s.Source, "// Auto-generated by test-runner") {
		t.Errorf("Generator override missing: %s", s.Source)
	}
}

func TestEmitShimGeneratorDefaultsApplied(t *testing.T) {
	// Header explicitly on so we can observe the generator default.
	s, err := EmitShim(&wrapper.Wrapper{Package: "p"}, Options{Header: true})
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if !strings.Contains(s.Source, "Auto-generated by mochi pkg lock") {
		t.Errorf("default generator not applied: %s", s.Source)
	}
}

func TestEmitShimEmptyOptionsHeaderOff(t *testing.T) {
	// Empty Options has Header=false; the shim has no banner.
	s, _ := EmitShim(&wrapper.Wrapper{Package: "p"}, Options{})
	if strings.Contains(s.Source, "Auto-generated") {
		t.Errorf("empty Options should not emit header: %s", s.Source)
	}
}

func TestEmitShimFunction(t *testing.T) {
	w := &wrapper.Wrapper{
		Package: "math2",
		Items: []wrapper.Item{
			{
				Name:       "add",
				SourceName: "math2.add",
				Kind:       wrapper.ItemFunc,
				Type: typemap.NewFun(
					typemap.NewScalar("int"),
					typemap.NewScalar("int"),
					typemap.NewScalar("int"),
				),
			},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "extern python fun add(int, int): int") {
		t.Errorf("missing extern fun: %s", s.Source)
	}
	if len(s.Decls) != 1 || s.Decls[0].Kind != DeclExternFun {
		t.Errorf("decls = %+v", s.Decls)
	}
}

func TestEmitShimAsyncFunctionRendersAsyncReturn(t *testing.T) {
	asyncReturn := typemap.NewAsync(typemap.NewScalar("bytes"))
	w := &wrapper.Wrapper{
		Package: "httpx",
		Items: []wrapper.Item{
			{
				Name:       "fetch_sync",
				SourceName: "httpx.fetch",
				Kind:       wrapper.ItemFunc,
				IsAsync:    true,
				Type:       typemap.NewFun(asyncReturn, typemap.NewScalar("string")),
			},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "extern python fun fetch_sync(string): async bytes") {
		t.Errorf("missing async signature: %s", s.Source)
	}
}

func TestEmitShimRecordRendersTypeAlias(t *testing.T) {
	rec := typemap.MochiType{
		Kind: typemap.KindRecord,
		Name: "Point",
		Fields: []typemap.MochiField{
			{Name: "x", Type: typemap.NewScalar("int")},
			{Name: "y", Type: typemap.NewScalar("int")},
		},
	}
	w := &wrapper.Wrapper{
		Package: "geom",
		Items: []wrapper.Item{
			{Name: "Point", SourceName: "geom.Point", Kind: wrapper.ItemRecord, Type: rec},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	for _, line := range []string{
		"type Point = {",
		"  x: int,",
		"  y: int",
		"}",
	} {
		if !strings.Contains(s.Source, line) {
			t.Errorf("missing line %q in:\n%s", line, s.Source)
		}
	}
	if s.Decls[0].Kind != DeclTypeAlias {
		t.Errorf("kind = %v", s.Decls[0].Kind)
	}
}

func TestEmitShimEmptyRecordOpaque(t *testing.T) {
	rec := typemap.MochiType{Kind: typemap.KindRecord, Name: "Empty"}
	w := &wrapper.Wrapper{
		Package: "p",
		Items: []wrapper.Item{
			{Name: "Empty", SourceName: "p.Empty", Kind: wrapper.ItemRecord, Type: rec},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "extern python type Empty") {
		t.Errorf("expected opaque extern, got: %s", s.Source)
	}
	if s.Decls[0].Kind != DeclExternType {
		t.Errorf("kind = %v", s.Decls[0].Kind)
	}
}

func TestEmitShimInterfaceOpaque(t *testing.T) {
	iface := typemap.MochiType{Kind: typemap.KindInterface, Name: "Greeter"}
	w := &wrapper.Wrapper{
		Package: "p",
		Items: []wrapper.Item{
			{Name: "Greeter", SourceName: "p.Greeter", Kind: wrapper.ItemInterface, Type: iface},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "extern python type Greeter") {
		t.Errorf("expected opaque interface, got: %s", s.Source)
	}
	if s.Decls[0].Kind != DeclExternType {
		t.Errorf("kind = %v", s.Decls[0].Kind)
	}
}

func TestEmitShimConstant(t *testing.T) {
	w := &wrapper.Wrapper{
		Package: "p",
		Items: []wrapper.Item{
			{
				Name:       "VERSION",
				SourceName: "p.VERSION",
				Kind:       wrapper.ItemConstant,
				Type:       typemap.NewScalar("string"),
			},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "extern python var VERSION: string") {
		t.Errorf("missing extern var: %s", s.Source)
	}
	if s.Decls[0].Kind != DeclExternVar {
		t.Errorf("kind = %v", s.Decls[0].Kind)
	}
}

func TestEmitShimGroupingOrder(t *testing.T) {
	// One of each kind; ensure they appear in the documented group order:
	// records, interfaces, constants, functions.
	rec := typemap.MochiType{
		Kind:   typemap.KindRecord,
		Name:   "Rec",
		Fields: []typemap.MochiField{{Name: "x", Type: typemap.NewScalar("int")}},
	}
	iface := typemap.MochiType{Kind: typemap.KindInterface, Name: "If"}
	fn := typemap.NewFun(typemap.NewScalar("int"))
	w := &wrapper.Wrapper{
		Package: "p",
		Items: []wrapper.Item{
			{Name: "fn", SourceName: "p.fn", Kind: wrapper.ItemFunc, Type: fn},
			{Name: "If", SourceName: "p.If", Kind: wrapper.ItemInterface, Type: iface},
			{Name: "VER", SourceName: "p.VER", Kind: wrapper.ItemConstant, Type: typemap.NewScalar("string")},
			{Name: "Rec", SourceName: "p.Rec", Kind: wrapper.ItemRecord, Type: rec},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	idxRec := strings.Index(s.Source, "type Rec =")
	idxIf := strings.Index(s.Source, "extern python type If")
	idxVar := strings.Index(s.Source, "extern python var VER")
	idxFn := strings.Index(s.Source, "extern python fun fn")
	if !(idxRec < idxIf && idxIf < idxVar && idxVar < idxFn) {
		t.Errorf("group order violated: rec=%d iface=%d var=%d fn=%d\n%s",
			idxRec, idxIf, idxVar, idxFn, s.Source)
	}
}

func TestEmitShimStableSourceNameOrder(t *testing.T) {
	w := &wrapper.Wrapper{
		Package: "p",
		Items: []wrapper.Item{
			{Name: "zeta", SourceName: "p.zeta", Kind: wrapper.ItemFunc, Type: typemap.NewFun(typemap.NewScalar("int"))},
			{Name: "alpha", SourceName: "p.alpha", Kind: wrapper.ItemFunc, Type: typemap.NewFun(typemap.NewScalar("int"))},
			{Name: "mu", SourceName: "p.mu", Kind: wrapper.ItemFunc, Type: typemap.NewFun(typemap.NewScalar("int"))},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	a := strings.Index(s.Source, "extern python fun alpha")
	m := strings.Index(s.Source, "extern python fun mu")
	z := strings.Index(s.Source, "extern python fun zeta")
	if !(a < m && m < z) {
		t.Errorf("not sorted: alpha=%d mu=%d zeta=%d\n%s", a, m, z, s.Source)
	}
}

func TestEmitShimSkipReportEmitted(t *testing.T) {
	w := &wrapper.Wrapper{
		Package: "p",
		Skipped: []errors.SkipReport{
			{ItemPath: "p.bad", Reason: errors.SkipNoComplexType, Detail: "complex"},
		},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "// SKIPPED items") {
		t.Errorf("missing SKIPPED header: %s", s.Source)
	}
	if !strings.Contains(s.Source, "//   p.bad (SkipNoComplexType)") {
		t.Errorf("missing skipped entry: %s", s.Source)
	}
}

func TestEmitShimSkipReportSuppressed(t *testing.T) {
	w := &wrapper.Wrapper{
		Package: "p",
		Skipped: []errors.SkipReport{
			{ItemPath: "p.bad", Reason: errors.SkipNoComplexType},
		},
	}
	opts := DefaultOptions()
	opts.IncludeSkipReport = false
	s, _ := EmitShim(w, opts)
	if strings.Contains(s.Source, "SKIPPED items") {
		t.Errorf("skip report should be off: %s", s.Source)
	}
}

func TestDeclKindString(t *testing.T) {
	cases := map[DeclKind]string{
		DeclExternFun:  "extern_fun",
		DeclTypeAlias:  "type_alias",
		DeclExternType: "extern_type",
		DeclExternVar:  "extern_var",
		DeclKind(999):  "unknown",
	}
	for k, want := range cases {
		if k.String() != want {
			t.Errorf("%d.String() = %s, want %s", k, k.String(), want)
		}
	}
}

func TestEmitShimDeterministicSHA256(t *testing.T) {
	w := &wrapper.Wrapper{
		Package: "p",
		Items: []wrapper.Item{
			{
				Name:       "add",
				SourceName: "p.add",
				Kind:       wrapper.ItemFunc,
				Type: typemap.NewFun(
					typemap.NewScalar("int"),
					typemap.NewScalar("int"),
					typemap.NewScalar("int"),
				),
			},
		},
	}
	a, _ := EmitShim(w, DefaultOptions())
	b, _ := EmitShim(w, DefaultOptions())
	if a.SHA256 != b.SHA256 {
		t.Errorf("non-deterministic: %s vs %s", a.SHA256, b.SHA256)
	}
}

func TestEmitShimNestedTypeRender(t *testing.T) {
	rec := typemap.MochiType{
		Kind: typemap.KindRecord,
		Name: "R",
		Fields: []typemap.MochiField{
			{Name: "data", Type: typemap.NewMap(typemap.NewScalar("string"),
				typemap.NewList(typemap.NewOptional(typemap.NewScalar("int"))))},
		},
	}
	w := &wrapper.Wrapper{
		Package: "p",
		Items:   []wrapper.Item{{Name: "R", SourceName: "p.R", Kind: wrapper.ItemRecord, Type: rec}},
	}
	s, _ := EmitShim(w, DefaultOptions())
	if !strings.Contains(s.Source, "data: map<string, list<int?>>") {
		t.Errorf("nested type render missing: %s", s.Source)
	}
}
