package freethread

import (
	"fmt"
	"sort"
	"strings"
)

// LockStrategy is the locking discipline the rendered shim picks
// based on whether the runtime is free-threaded.
type LockStrategy int

const (
	// LockGIL is the legacy strategy: rely on the CPython GIL to
	// serialise refcount + dict writes; only acquire an explicit
	// Python lock when crossing thread boundaries the wrapper
	// surfaced as `extern python` boundaries.
	LockGIL LockStrategy = iota

	// LockPyMutex is the PEP 703 strategy: PyMutex-style primitive
	// for fine-grained per-object locks; atomic refcount.
	LockPyMutex
)

// String renders the strategy for diagnostics.
func (s LockStrategy) String() string {
	switch s {
	case LockGIL:
		return "gil"
	case LockPyMutex:
		return "pymutex"
	default:
		return "unknown"
	}
}

// LockShim captures one mutex region the wrapper synthesiser needs.
// Name is the symbol Python source will export; CriticalSection lists
// the (module, attribute) tuples the lock guards (so PyMutex-aware
// builds can map them onto the per-object lock).
type LockShim struct {
	Name             string
	CriticalSection []QualifiedAttr
}

// QualifiedAttr is a `module.attr` pair the lock guards.
type QualifiedAttr struct {
	Module string
	Attr   string
}

// Validate enforces the shim invariants the renderer relies on.
func (s LockShim) Validate() error {
	if s.Name == "" {
		return fmt.Errorf("freethread: LockShim Name must be non-empty")
	}
	if !isPyIdent(s.Name) {
		return fmt.Errorf("freethread: LockShim Name %q is not a Python identifier", s.Name)
	}
	seen := map[QualifiedAttr]struct{}{}
	for _, q := range s.CriticalSection {
		if q.Module == "" || q.Attr == "" {
			return fmt.Errorf("freethread: LockShim CriticalSection entry %+v has empty field", q)
		}
		if _, dup := seen[q]; dup {
			return fmt.Errorf("freethread: LockShim CriticalSection duplicate %+v", q)
		}
		seen[q] = struct{}{}
	}
	return nil
}

// RenderLockShim emits the Python module source that supplies the
// `<name>` lock object. The body branches on `sys` reporting the
// free-threaded build (`sys._is_gil_enabled() is False`) at import
// time so the same shim source ships on both runtimes.
//
// The renderer is deterministic: shims sort their CriticalSection
// list (module, attr) so golden tests stay stable across runs.
func RenderLockShim(shim LockShim, strategy LockStrategy) (string, error) {
	if err := shim.Validate(); err != nil {
		return "", err
	}
	cs := append([]QualifiedAttr(nil), shim.CriticalSection...)
	sort.Slice(cs, func(i, j int) bool {
		if cs[i].Module != cs[j].Module {
			return cs[i].Module < cs[j].Module
		}
		return cs[i].Attr < cs[j].Attr
	})

	var b strings.Builder
	b.WriteString("# AUTOGENERATED by freethread.RenderLockShim; do not edit.\n")
	b.WriteString("import sys, threading\n")
	b.WriteString("\n")
	switch strategy {
	case LockPyMutex:
		b.WriteString("# Free-threaded build: prefer the PEP 703 PyMutex bridge\n")
		b.WriteString("# threading._PyMutex is the public name once 3.13t / 3.14t lands;\n")
		b.WriteString("# we fall back to threading.Lock when the attribute is missing\n")
		b.WriteString("# so wheels that target 3.13.0t (pre-name-change) still link.\n")
		b.WriteString("if hasattr(threading, '_PyMutex'):\n")
		b.WriteString("    _LockKind = threading._PyMutex\n")
		b.WriteString("else:\n")
		b.WriteString("    _LockKind = threading.Lock\n")
	default:
		b.WriteString("# Legacy GIL build: a single threading.Lock is enough; the GIL\n")
		b.WriteString("# already serialises refcount + dict writes.\n")
		b.WriteString("_LockKind = threading.Lock\n")
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "%s = _LockKind()\n", shim.Name)
	b.WriteString("\n")
	b.WriteString("# Critical sections this lock guards (for telemetry + diagnostics).\n")
	fmt.Fprintf(&b, "%s_GUARDS = (\n", shim.Name)
	for _, q := range cs {
		fmt.Fprintf(&b, "    (%q, %q),\n", q.Module, q.Attr)
	}
	b.WriteString(")\n")
	b.WriteString("\n")
	b.WriteString("# Runtime self-check: warn loudly if a free-threaded build imports\n")
	b.WriteString("# a shim rendered for the GIL strategy.\n")
	if strategy == LockGIL {
		b.WriteString("if hasattr(sys, '_is_gil_enabled') and not sys._is_gil_enabled():\n")
		b.WriteString("    import warnings\n")
		fmt.Fprintf(&b, "    warnings.warn('%s rendered for GIL but interpreter is free-threaded', RuntimeWarning)\n", shim.Name)
	}
	return b.String(), nil
}

func isPyIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r == '_':
		case r >= '0' && r <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}
