package freethread

import (
	"strings"
	"testing"
)

func TestLockStrategyString(t *testing.T) {
	cases := map[LockStrategy]string{
		LockGIL:     "gil",
		LockPyMutex: "pymutex",
	}
	for s, want := range cases {
		if got := s.String(); got != want {
			t.Errorf("%d.String() = %q, want %q", s, got, want)
		}
	}
	// unknown sentinel
	if got := LockStrategy(99).String(); got != "unknown" {
		t.Errorf("unknown.String() = %q", got)
	}
}

func TestRenderLockShimValidates(t *testing.T) {
	cases := []LockShim{
		{Name: ""},
		{Name: "1bad"},
		{Name: "ok", CriticalSection: []QualifiedAttr{{Module: "", Attr: "x"}}},
		{Name: "ok", CriticalSection: []QualifiedAttr{{Module: "m", Attr: ""}}},
		{Name: "ok", CriticalSection: []QualifiedAttr{{Module: "m", Attr: "x"}, {Module: "m", Attr: "x"}}},
	}
	for i, shim := range cases {
		if _, err := RenderLockShim(shim, LockGIL); err == nil {
			t.Errorf("case %d: expected validate error", i)
		}
	}
}

func TestRenderLockShimGIL(t *testing.T) {
	shim := LockShim{Name: "demo_lock", CriticalSection: []QualifiedAttr{
		{Module: "demo", Attr: "shared_state"},
	}}
	src, err := RenderLockShim(shim, LockGIL)
	if err != nil {
		t.Fatalf("RenderLockShim: %v", err)
	}
	mustContain := []string{
		"AUTOGENERATED",
		"import sys, threading",
		"_LockKind = threading.Lock",
		"demo_lock = _LockKind()",
		"demo_lock_GUARDS = (",
		`("demo", "shared_state"),`,
		"sys._is_gil_enabled",
		"RuntimeWarning",
	}
	for _, s := range mustContain {
		if !strings.Contains(src, s) {
			t.Errorf("GIL shim missing %q\n--- got ---\n%s", s, src)
		}
	}
	// the GIL shim must not reference PyMutex
	if strings.Contains(src, "_PyMutex") {
		t.Error("GIL shim should not reference _PyMutex")
	}
}

func TestRenderLockShimPyMutex(t *testing.T) {
	shim := LockShim{Name: "x_lock", CriticalSection: []QualifiedAttr{
		{Module: "a", Attr: "y"},
		{Module: "a", Attr: "x"},
		{Module: "b", Attr: "z"},
	}}
	src, err := RenderLockShim(shim, LockPyMutex)
	if err != nil {
		t.Fatalf("RenderLockShim: %v", err)
	}
	mustContain := []string{
		"hasattr(threading, '_PyMutex')",
		"_LockKind = threading._PyMutex",
		"_LockKind = threading.Lock",
		"x_lock = _LockKind()",
	}
	for _, s := range mustContain {
		if !strings.Contains(src, s) {
			t.Errorf("PyMutex shim missing %q\n--- got ---\n%s", s, src)
		}
	}
	// PyMutex shim should not emit the GIL-rendered-on-free-threaded warning.
	if strings.Contains(src, "RuntimeWarning") {
		t.Error("PyMutex shim should not emit RuntimeWarning")
	}
	// guards should be sorted: (a,x) before (a,y) before (b,z).
	ax := strings.Index(src, `("a", "x")`)
	ay := strings.Index(src, `("a", "y")`)
	bz := strings.Index(src, `("a", "z")`)
	if ax == -1 || ay == -1 {
		t.Fatalf("missing guards; src = %s", src)
	}
	if !(ax < ay) {
		t.Errorf("guard ordering: (a,x) should precede (a,y), got %d %d", ax, ay)
	}
	if bz != -1 {
		t.Error("unexpected (a,z) entry")
	}
}

func TestRenderLockShimDefaultStrategy(t *testing.T) {
	// Unknown strategy falls through to the GIL branch.
	shim := LockShim{Name: "x"}
	src, err := RenderLockShim(shim, LockStrategy(99))
	if err != nil {
		t.Fatalf("RenderLockShim: %v", err)
	}
	if !strings.Contains(src, "_LockKind = threading.Lock") {
		t.Errorf("default branch missing GIL fallback")
	}
}

func TestIsPyIdent(t *testing.T) {
	yes := []string{"a", "abc", "_abc", "a1", "x_y"}
	no := []string{"", "1abc", "-a", "abc-def"}
	for _, s := range yes {
		if !isPyIdent(s) {
			t.Errorf("isPyIdent(%q) = false", s)
		}
	}
	for _, s := range no {
		if isPyIdent(s) {
			t.Errorf("isPyIdent(%q) = true", s)
		}
	}
}
