package pypackage

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"sort"
	"strings"

	"github.com/mochilang/mochi-python/typemap"
)

// Generator identifies who produced the artifact. Stamped into WHEEL and the
// auto-generated comment lines so emit diffs are self-explanatory.
const Generator = "mochi pkg build (MEP-71)"

// PyprojectTOML returns the canonical pyproject.toml for the package. The
// build-backend is `mochi_build`, the bundled PEP 517 backend that
// MochiBuildBackend() renders below.
func PyprojectTOML(p Package) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by " + Generator + ". Do not edit by hand.\n\n")
	b.WriteString("[build-system]\n")
	b.WriteString(`requires = ["mochi-python-runtime>=0.6,<0.7"]` + "\n")
	b.WriteString(`build-backend = "mochi_build"` + "\n")
	b.WriteString(`backend-path = ["."]` + "\n\n")
	b.WriteString("[project]\n")
	fmt.Fprintf(&b, "name = %q\n", p.Distribution)
	fmt.Fprintf(&b, "version = %q\n", p.Version)
	fmt.Fprintf(&b, "description = %q\n", p.Summary)
	if p.RequiresPython != "" {
		fmt.Fprintf(&b, "requires-python = %q\n", p.RequiresPython)
	}
	if p.License != "" {
		fmt.Fprintf(&b, "license = { text = %q }\n", p.License)
	}
	if p.HomePage != "" {
		fmt.Fprintf(&b, "urls = { Homepage = %q }\n", p.HomePage)
	}
	if p.Author != "" {
		fmt.Fprintf(&b, "authors = [{ name = %q }]\n", p.Author)
	}
	if len(p.Dependencies) > 0 {
		b.WriteString("dependencies = [\n")
		deps := append([]string(nil), p.Dependencies...)
		sort.Strings(deps)
		for _, d := range deps {
			fmt.Fprintf(&b, "    %q,\n", d)
		}
		b.WriteString("]\n")
	}
	return b.String()
}

// PKGInfo returns the METADATA-1.2 body that ships in PKG-INFO inside the
// sdist and in <name>-<version>.dist-info/METADATA inside the wheel.
func PKGInfo(p Package) string {
	var b strings.Builder
	b.WriteString("Metadata-Version: 2.1\n")
	fmt.Fprintf(&b, "Name: %s\n", p.Distribution)
	fmt.Fprintf(&b, "Version: %s\n", p.Version)
	fmt.Fprintf(&b, "Summary: %s\n", p.Summary)
	if p.HomePage != "" {
		fmt.Fprintf(&b, "Home-page: %s\n", p.HomePage)
	}
	if p.Author != "" {
		fmt.Fprintf(&b, "Author: %s\n", p.Author)
	}
	if p.License != "" {
		fmt.Fprintf(&b, "License: %s\n", p.License)
	}
	if p.RequiresPython != "" {
		fmt.Fprintf(&b, "Requires-Python: %s\n", p.RequiresPython)
	}
	deps := append([]string(nil), p.Dependencies...)
	sort.Strings(deps)
	for _, d := range deps {
		fmt.Fprintf(&b, "Requires-Dist: %s\n", d)
	}
	b.WriteString("\n")
	b.WriteString(p.Summary)
	b.WriteString("\n")
	return b.String()
}

// WheelMetadata returns the WHEEL marker per PEP 427.
func WheelMetadata() string {
	var b strings.Builder
	b.WriteString("Wheel-Version: 1.0\n")
	b.WriteString("Generator: " + Generator + "\n")
	b.WriteString("Root-Is-Purelib: true\n")
	b.WriteString("Tag: py3-none-any\n")
	return b.String()
}

// InitPy returns the package's runtime __init__.py. The body re-exports the
// Mochi runtime entry point; the actual implementation is loaded by the
// PEP 517 backend at build time and emitted as a sibling .so or .py file.
func InitPy(p Package) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by " + Generator + ". Do not edit by hand.\n")
	b.WriteString(`"""` + p.Distribution + " (compiled from Mochi).\n\n")
	b.WriteString(p.Summary + `"""` + "\n")
	b.WriteString("from .mochi_runtime import *  # noqa: F401,F403\n")
	b.WriteString("__all__ = [\n")
	names := exportNames(p)
	for _, n := range names {
		fmt.Fprintf(&b, "    %q,\n", n)
	}
	b.WriteString("]\n")
	return b.String()
}

// InitPYI returns the typed surface stub. Downstream typing tools (mypy,
// pyright) consume this without running the Mochi runtime.
func InitPYI(p Package) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by " + Generator + ". Do not edit by hand.\n")
	imports := pyImportsFor(p)
	if len(imports) > 0 {
		for _, line := range imports {
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
	for _, e := range p.Exports {
		switch e.Kind {
		case ExportFunc:
			renderFuncSig(&b, e)
		case ExportRecord:
			renderRecord(&b, e)
		case ExportInterface:
			renderInterface(&b, e)
		case ExportConstant:
			renderConstant(&b, e)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderFuncSig(b *strings.Builder, e Export) {
	params := e.Type.FunParams()
	ret := e.Type.Return()
	fmt.Fprintf(b, "def %s(", e.Name)
	for i, p := range params {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "arg%d: %s", i, pyAnnotation(p))
	}
	fmt.Fprintf(b, ") -> %s: ...\n", pyAnnotation(ret))
}

func renderRecord(b *strings.Builder, e Export) {
	fmt.Fprintf(b, "class %s:\n", e.Name)
	if len(e.Type.Fields) == 0 {
		b.WriteString("    ...\n")
		return
	}
	for _, f := range e.Type.Fields {
		fmt.Fprintf(b, "    %s: %s\n", f.Name, pyAnnotation(f.Type))
	}
}

func renderInterface(b *strings.Builder, e Export) {
	fmt.Fprintf(b, "class %s(Protocol):\n", e.Name)
	if len(e.Type.Methods) == 0 {
		b.WriteString("    ...\n")
		return
	}
	for _, m := range e.Type.Methods {
		prefix := "def"
		if m.IsAsync {
			prefix = "async def"
		}
		fmt.Fprintf(b, "    %s %s(self", prefix, m.Name)
		for i, p := range m.Params {
			fmt.Fprintf(b, ", arg%d: %s", i, pyAnnotation(p))
		}
		fmt.Fprintf(b, ") -> %s: ...\n", pyAnnotation(m.Return))
	}
}

func renderConstant(b *strings.Builder, e Export) {
	fmt.Fprintf(b, "%s: %s\n", e.Name, pyAnnotation(e.Type))
}

// pyAnnotation lowers a MochiType to a Python type annotation. Symmetric to
// the Phase 5 wrapper's reverse direction but in the publish direction the
// arrow points outward: scalars become builtins, records / interfaces become
// type names, lists / sets become typing.List / typing.Set, etc.
func pyAnnotation(t typemap.MochiType) string {
	switch t.Kind {
	case typemap.KindScalar:
		return pyScalar(t.Name)
	case typemap.KindList:
		return "list[" + pyAnnotation(t.Params[0]) + "]"
	case typemap.KindSet:
		return "set[" + pyAnnotation(t.Params[0]) + "]"
	case typemap.KindMap:
		return "dict[" + pyAnnotation(t.Params[0]) + ", " + pyAnnotation(t.Params[1]) + "]"
	case typemap.KindOptional:
		return "Optional[" + pyAnnotation(t.Params[0]) + "]"
	case typemap.KindSum:
		parts := make([]string, len(t.Params))
		for i, p := range t.Params {
			parts[i] = pyAnnotation(p)
		}
		return "Union[" + strings.Join(parts, ", ") + "]"
	case typemap.KindTuple:
		parts := make([]string, len(t.Params))
		for i, p := range t.Params {
			parts[i] = pyAnnotation(p)
		}
		return "tuple[" + strings.Join(parts, ", ") + "]"
	case typemap.KindAsync:
		return "Awaitable[" + pyAnnotation(t.Params[0]) + "]"
	case typemap.KindStream:
		return "AsyncIterator[" + pyAnnotation(t.Params[0]) + "]"
	case typemap.KindFun:
		params := t.FunParams()
		parts := make([]string, len(params))
		for i, p := range params {
			parts[i] = pyAnnotation(p)
		}
		return "Callable[[" + strings.Join(parts, ", ") + "], " + pyAnnotation(t.Return()) + "]"
	case typemap.KindRef:
		return t.Name
	case typemap.KindRecord:
		if t.Name == "" {
			return "Any"
		}
		return t.Name
	case typemap.KindInterface:
		if t.Name == "" {
			return "Any"
		}
		return t.Name
	case typemap.KindTypeVar:
		return t.Name
	}
	return "Any"
}

func pyScalar(name string) string {
	switch name {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string":
		return "str"
	case "bytes":
		return "bytes"
	case "None":
		return "None"
	case "Any":
		return "Any"
	}
	return name
}

// pyImportsFor scans the package's exports for type shapes that need typing
// imports (Optional, Union, Awaitable, AsyncIterator, Callable, Protocol)
// and produces the minimal `from typing import ...` set.
func pyImportsFor(p Package) []string {
	seen := map[string]bool{}
	for _, e := range p.Exports {
		if e.Kind == ExportInterface {
			seen["Protocol"] = true
		}
		walkTyping(e.Type, seen)
	}
	if len(seen) == 0 {
		return nil
	}
	names := make([]string, 0, len(seen))
	for n := range seen {
		names = append(names, n)
	}
	sort.Strings(names)
	return []string{"from typing import " + strings.Join(names, ", ")}
}

func walkTyping(t typemap.MochiType, seen map[string]bool) {
	switch t.Kind {
	case typemap.KindOptional:
		seen["Optional"] = true
		walkParams(t, seen)
	case typemap.KindSum:
		seen["Union"] = true
		walkParams(t, seen)
	case typemap.KindAsync:
		seen["Awaitable"] = true
		walkParams(t, seen)
	case typemap.KindStream:
		seen["AsyncIterator"] = true
		walkParams(t, seen)
	case typemap.KindFun:
		seen["Callable"] = true
		walkParams(t, seen)
	case typemap.KindScalar:
		if t.Name == "Any" {
			seen["Any"] = true
		}
	case typemap.KindList, typemap.KindSet, typemap.KindMap, typemap.KindTuple:
		walkParams(t, seen)
	case typemap.KindRecord:
		for _, f := range t.Fields {
			walkTyping(f.Type, seen)
		}
	case typemap.KindInterface:
		for _, m := range t.Methods {
			for _, p := range m.Params {
				walkTyping(p, seen)
			}
			walkTyping(m.Return, seen)
		}
	}
}

func walkParams(t typemap.MochiType, seen map[string]bool) {
	for _, p := range t.Params {
		walkTyping(p, seen)
	}
}

func exportNames(p Package) []string {
	names := make([]string, 0, len(p.Exports))
	for _, e := range p.Exports {
		names = append(names, e.Name)
	}
	sort.Strings(names)
	return names
}

// MochiBuildBackend returns the bundled PEP 517 build-backend Python source
// (`mochi_build/__init__.py`). The backend defers to `mochi pkg build
// --target=python-package --workdir <build-dir>` and copies the resulting
// wheel / sdist into the build context.
func MochiBuildBackend() string {
	return `"""mochi_build PEP 517 backend. Generated by ` + Generator + `."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path


def _run_mochi(target: str, dest: Path, config_settings: dict | None) -> Path:
    dest.mkdir(parents=True, exist_ok=True)
    cmd = [
        "mochi", "pkg", "build",
        "--target=python-package",
        f"--format={target}",
        f"--out={dest}",
    ]
    if config_settings:
        for k, v in config_settings.items():
            cmd.append(f"--config-setting={k}={v}")
    subprocess.run(cmd, check=True)
    artifacts = sorted(dest.glob(f"*.{target}" if target == "whl" else "*.tar.gz"))
    if not artifacts:
        raise RuntimeError(f"mochi pkg build produced no {target} artifact")
    return artifacts[-1]


def build_wheel(wheel_directory: str, config_settings: dict | None = None,
                metadata_directory: str | None = None) -> str:
    art = _run_mochi("whl", Path(wheel_directory), config_settings)
    return art.name


def build_sdist(sdist_directory: str, config_settings: dict | None = None) -> str:
    art = _run_mochi("sdist", Path(sdist_directory), config_settings)
    return art.name


def get_requires_for_build_wheel(config_settings: dict | None = None) -> list[str]:
    return []


def get_requires_for_build_sdist(config_settings: dict | None = None) -> list[str]:
    return []


def prepare_metadata_for_build_wheel(metadata_directory: str,
                                     config_settings: dict | None = None) -> str:
    dest = Path(metadata_directory)
    info = dest / (os.environ.get("MOCHI_DIST_INFO", "mochi-0.0.0.dist-info"))
    info.mkdir(parents=True, exist_ok=True)
    return info.name
`
}

// RecordEntry is one row in a wheel's RECORD file. Hash is the base64-urlsafe
// SHA-256 of the file body; Size is the byte count. METADATA / RECORD itself
// are emitted with empty hash/size by convention.
type RecordEntry struct {
	Path string
	Hash string
	Size int
}

// RecordLine renders one entry per PEP 376 / 491.
func RecordLine(e RecordEntry) string {
	if e.Hash == "" && e.Size == 0 {
		return e.Path + ",,"
	}
	return fmt.Sprintf("%s,sha256=%s,%d", e.Path, e.Hash, e.Size)
}

// HashBody returns the base64-urlsafe SHA-256 of body, with trailing `=`
// padding stripped per PEP 376.
func HashBody(body string) string {
	sum := sha256.Sum256([]byte(body))
	return strings.TrimRight(base64.URLEncoding.EncodeToString(sum[:]), "=")
}
