package subproc

import (
	"fmt"
	"strings"
)

// WorkerOptions configures the Python worker source RenderWorker
// emits. ModuleImport is the `from <pkg> import a, b, c` line that
// brings the user surface into scope. Methods is the closed list of
// callable names the worker dispatches; calls to names outside the
// list return CodeMethodNotFound. Async, when true, wraps each
// dispatch in `await` and drives the loop via `asyncio.run`.
type WorkerOptions struct {
	ModuleImport string
	Methods      []string
	Async        bool
}

// Validate rejects worker configurations the renderer cannot honour:
// empty ModuleImport, empty Methods, or method names that are not
// Python identifiers. The check is conservative — the call surface
// will be re-validated by the Python interpreter at startup anyway,
// but failing here gives the user a Mochi-side error instead of an
// opaque traceback when the worker first runs.
func (o WorkerOptions) Validate() error {
	if strings.TrimSpace(o.ModuleImport) == "" {
		return fmt.Errorf("subproc: WorkerOptions.ModuleImport is empty")
	}
	if len(o.Methods) == 0 {
		return fmt.Errorf("subproc: WorkerOptions.Methods is empty")
	}
	for _, m := range o.Methods {
		if !isPythonIdentifier(m) {
			return fmt.Errorf("subproc: WorkerOptions.Methods contains invalid identifier %q", m)
		}
	}
	return nil
}

func isPythonIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if r == '_' {
			continue
		}
		if r >= 'a' && r <= 'z' {
			continue
		}
		if r >= 'A' && r <= 'Z' {
			continue
		}
		if i > 0 && r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return true
}

// RenderWorker emits the Python source for the JSON-RPC stdio worker
// that the host subprocess client talks to. The worker:
//
//  1. Imports the user surface.
//  2. Reads newline-delimited JSON-RPC 2.0 requests from stdin.
//  3. Dispatches each request to the named method (positional params)
//     and writes the JSON-RPC 2.0 response to stdout.
//  4. Maps Python exceptions to CodeInternalError responses with the
//     exception text in Message.
//  5. Returns CodeMethodNotFound for unlisted method names.
//
// The async variant wraps each call in `await fn(*args)` and runs the
// main loop under `asyncio.run`. Mixed sync/async worker surfaces are
// possible (sub-phase 14.4) but out of scope here; the bridge picks
// per-worker based on the imported surface's dominant style.
func RenderWorker(opts WorkerOptions) (string, error) {
	if err := opts.Validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Generated by MEP-71 subproc. Do not edit.\n")
	b.WriteString("import json\n")
	b.WriteString("import sys\n")
	if opts.Async {
		b.WriteString("import asyncio\n")
	}
	b.WriteString(opts.ModuleImport)
	if !strings.HasSuffix(opts.ModuleImport, "\n") {
		b.WriteString("\n")
	}
	b.WriteString("\n")
	b.WriteString("_METHODS = {\n")
	for _, m := range opts.Methods {
		fmt.Fprintf(&b, "    %q: %s,\n", m, m)
	}
	b.WriteString("}\n\n")

	b.WriteString("_PARSE_ERROR = -32700\n")
	b.WriteString("_INVALID_REQUEST = -32600\n")
	b.WriteString("_METHOD_NOT_FOUND = -32601\n")
	b.WriteString("_INTERNAL_ERROR = -32603\n\n")

	b.WriteString("def _error(req_id, code, message):\n")
	b.WriteString(`    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": code, "message": message}}` + "\n")
	b.WriteString("\n")
	b.WriteString("def _ok(req_id, result):\n")
	b.WriteString(`    return {"jsonrpc": "2.0", "id": req_id, "result": result}` + "\n")
	b.WriteString("\n")

	if opts.Async {
		b.WriteString("async def _dispatch(req):\n")
	} else {
		b.WriteString("def _dispatch(req):\n")
	}
	b.WriteString("    req_id = req.get(\"id\", 0)\n")
	b.WriteString("    method = req.get(\"method\")\n")
	b.WriteString("    params = req.get(\"params\") or []\n")
	b.WriteString("    if method not in _METHODS:\n")
	b.WriteString("        return _error(req_id, _METHOD_NOT_FOUND, \"method not found: \" + str(method))\n")
	b.WriteString("    try:\n")
	if opts.Async {
		b.WriteString("        result = await _METHODS[method](*params)\n")
	} else {
		b.WriteString("        result = _METHODS[method](*params)\n")
	}
	b.WriteString("    except Exception as exc:\n")
	b.WriteString("        return _error(req_id, _INTERNAL_ERROR, repr(exc))\n")
	b.WriteString("    return _ok(req_id, result)\n\n")

	if opts.Async {
		b.WriteString("async def _main():\n")
		b.WriteString("    for line in sys.stdin:\n")
		b.WriteString("        line = line.strip()\n")
		b.WriteString("        if not line:\n")
		b.WriteString("            continue\n")
		b.WriteString("        try:\n")
		b.WriteString("            req = json.loads(line)\n")
		b.WriteString("        except Exception as exc:\n")
		b.WriteString("            resp = _error(0, _PARSE_ERROR, repr(exc))\n")
		b.WriteString("        else:\n")
		b.WriteString("            if req.get(\"jsonrpc\") != \"2.0\":\n")
		b.WriteString("                resp = _error(req.get(\"id\", 0), _INVALID_REQUEST, \"jsonrpc != 2.0\")\n")
		b.WriteString("            else:\n")
		b.WriteString("                resp = await _dispatch(req)\n")
		b.WriteString("        sys.stdout.write(json.dumps(resp))\n")
		b.WriteString("        sys.stdout.write(\"\\n\")\n")
		b.WriteString("        sys.stdout.flush()\n\n")
		b.WriteString("if __name__ == \"__main__\":\n")
		b.WriteString("    asyncio.run(_main())\n")
	} else {
		b.WriteString("def _main():\n")
		b.WriteString("    for line in sys.stdin:\n")
		b.WriteString("        line = line.strip()\n")
		b.WriteString("        if not line:\n")
		b.WriteString("            continue\n")
		b.WriteString("        try:\n")
		b.WriteString("            req = json.loads(line)\n")
		b.WriteString("        except Exception as exc:\n")
		b.WriteString("            resp = _error(0, _PARSE_ERROR, repr(exc))\n")
		b.WriteString("        else:\n")
		b.WriteString("            if req.get(\"jsonrpc\") != \"2.0\":\n")
		b.WriteString("                resp = _error(req.get(\"id\", 0), _INVALID_REQUEST, \"jsonrpc != 2.0\")\n")
		b.WriteString("            else:\n")
		b.WriteString("                resp = _dispatch(req)\n")
		b.WriteString("        sys.stdout.write(json.dumps(resp))\n")
		b.WriteString("        sys.stdout.write(\"\\n\")\n")
		b.WriteString("        sys.stdout.flush()\n\n")
		b.WriteString("if __name__ == \"__main__\":\n")
		b.WriteString("    _main()\n")
	}
	return b.String(), nil
}
