package wrapper

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mochilang/mochi-python/typemap"
)

// renderPy produces the contents of <Module>.py for the given Wrapper.
func renderPy(w *Wrapper) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by mochi pkg lock — do not edit.\n")
	b.WriteString("# MEP-71 wrapper for source package: ")
	b.WriteString(w.Package)
	b.WriteString(".\n")
	b.WriteString("\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("\n")
	if needsAsyncio(w) {
		b.WriteString("import asyncio\n")
	}
	b.WriteString("import ")
	b.WriteString(w.Package)
	b.WriteString(" as _src\n")
	b.WriteString("\n")
	b.WriteString("from ._mochi_wrap import ")
	helpers := wrapperHelpers(w)
	for i, h := range helpers {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(h)
	}
	b.WriteString("\n\n")

	for _, item := range w.Items {
		switch item.Kind {
		case ItemFunc:
			renderFunc(&b, w, item)
		case ItemRecord:
			renderRecord(&b, item)
		case ItemInterface:
			renderInterface(&b, item)
		case ItemConstant:
			renderConstant(&b, item)
		}
		b.WriteString("\n")
	}

	if w.Loop == EventLoopPersistent && hasAsync(w) {
		b.WriteString("# Persistent asyncio event loop, used by every async shim.\n")
		b.WriteString("_MOCHI_LOOP = _persistent_loop()\n")
	}
	return b.String()
}

func renderFunc(b *strings.Builder, w *Wrapper, item Item) {
	params := item.Type.FunParams()
	ret := item.Type.Return()
	bare := lastDot(item.SourceName)
	signature := paramSignature(params)
	if item.IsAsync {
		callForm := fmt.Sprintf("_src.%s(%s)", bare, signature)
		var runLine string
		if w.Loop == EventLoopPersistent {
			runLine = fmt.Sprintf("    return _MOCHI_LOOP.run_until_complete(%s)\n", callForm)
		} else {
			runLine = fmt.Sprintf("    return _run_async(%s)\n", callForm)
		}
		fmt.Fprintf(b, "def %s(%s):\n", item.Name, signature)
		b.WriteString(runLine)
		// Async-marked direct entry: lets the Mochi side opt into the async colour
		// pass once Phase 12 lands. Until then the _sync entry is the supported form.
		fmt.Fprintf(b, "\n\nasync def %s_async(%s):\n", strings.TrimSuffix(item.Name, "_sync"), signature)
		fmt.Fprintf(b, "    return await _src.%s(%s)\n", bare, signature)
		return
	}
	fmt.Fprintf(b, "def %s(%s):\n", item.Name, signature)
	fmt.Fprintf(b, "    return _src.%s(%s)\n", bare, signature)
	if isIteratorReturn(ret) {
		// Companion materialiser keeps the lazy form available too.
		fmt.Fprintf(b, "\n\ndef %s_list(%s):\n", item.Name, signature)
		fmt.Fprintf(b, "    return _materialise_iter(_src.%s(%s))\n", bare, signature)
	}
}

func renderRecord(b *strings.Builder, item Item) {
	bare := lastDot(item.SourceName)
	fmt.Fprintf(b, "%s = _src.%s\n", item.Name, bare)
	if len(item.Type.Fields) == 0 {
		return
	}
	fmt.Fprintf(b, "\n\ndef _%s_to_mochi_dict(value):\n", item.Name)
	b.WriteString("    return {\n")
	names := make([]string, 0, len(item.Type.Fields))
	for _, f := range item.Type.Fields {
		names = append(names, f.Name)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(b, "        %q: _to_mochi_dict(getattr(value, %q)),\n", n, n)
	}
	b.WriteString("    }\n")
}

func renderInterface(b *strings.Builder, item Item) {
	bare := lastDot(item.SourceName)
	fmt.Fprintf(b, "%s = _src.%s\n", item.Name, bare)
}

func renderConstant(b *strings.Builder, item Item) {
	bare := lastDot(item.SourceName)
	fmt.Fprintf(b, "%s = _src.%s\n", item.Name, bare)
}

// renderPYI produces the contents of <Module>.pyi for the given Wrapper. It
// is a minimal stub: types come from typemap MochiType -> Python annotation
// rendering. The .pyi does not import the source module; downstream typing
// only needs the wrapper's surface.
func renderPYI(w *Wrapper) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by mochi pkg lock — do not edit.\n")
	b.WriteString("# MEP-71 wrapper stub for source package: ")
	b.WriteString(w.Package)
	b.WriteString(".\n")
	b.WriteString("\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("from typing import Any, AsyncIterator, Awaitable, Callable, Iterable, Mapping, Optional, Protocol, Tuple, TypedDict, Union\n")
	b.WriteString("\n")

	for _, item := range w.Items {
		switch item.Kind {
		case ItemFunc:
			renderFuncPYI(&b, item)
		case ItemRecord:
			renderRecordPYI(&b, item)
		case ItemInterface:
			renderInterfacePYI(&b, item)
		case ItemConstant:
			fmt.Fprintf(&b, "%s: %s\n", item.Name, renderPyAnno(item.Type))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderFuncPYI(b *strings.Builder, item Item) {
	params := item.Type.FunParams()
	ret := item.Type.Return()
	var parts []string
	for i, p := range params {
		parts = append(parts, fmt.Sprintf("arg%d: %s", i, renderPyAnno(p)))
	}
	fmt.Fprintf(b, "def %s(%s) -> %s: ...\n", item.Name, strings.Join(parts, ", "), renderPyAnno(ret))
	if item.IsAsync {
		fmt.Fprintf(b, "async def %s_async(%s) -> %s: ...\n",
			strings.TrimSuffix(item.Name, "_sync"),
			strings.Join(parts, ", "),
			renderPyAnno(ret),
		)
	}
}

func renderRecordPYI(b *strings.Builder, item Item) {
	fmt.Fprintf(b, "class %s(TypedDict, total=False):\n", item.Name)
	if len(item.Type.Fields) == 0 {
		b.WriteString("    pass\n")
		return
	}
	names := make([]string, 0, len(item.Type.Fields))
	idx := make(map[string]typemap.MochiField, len(item.Type.Fields))
	for _, f := range item.Type.Fields {
		names = append(names, f.Name)
		idx[f.Name] = f
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(b, "    %s: %s\n", n, renderPyAnno(idx[n].Type))
	}
}

func renderInterfacePYI(b *strings.Builder, item Item) {
	fmt.Fprintf(b, "class %s(Protocol):\n", item.Name)
	if len(item.Type.Methods) == 0 {
		b.WriteString("    pass\n")
		return
	}
	names := make([]string, 0, len(item.Type.Methods))
	idx := make(map[string]typemap.MochiMethod, len(item.Type.Methods))
	for _, m := range item.Type.Methods {
		names = append(names, m.Name)
		idx[m.Name] = m
	}
	sort.Strings(names)
	for _, n := range names {
		mm := idx[n]
		var parts []string
		parts = append(parts, "self")
		for i, p := range mm.Params {
			parts = append(parts, fmt.Sprintf("arg%d: %s", i, renderPyAnno(p)))
		}
		ret := renderPyAnno(mm.Return)
		if mm.IsAsync {
			fmt.Fprintf(b, "    async def %s(%s) -> %s: ...\n", n, strings.Join(parts, ", "), ret)
		} else {
			fmt.Fprintf(b, "    def %s(%s) -> %s: ...\n", n, strings.Join(parts, ", "), ret)
		}
	}
}

func renderPyAnno(t typemap.MochiType) string {
	switch t.Kind {
	case typemap.KindScalar:
		return scalarPyAnno(t.Name)
	case typemap.KindRef, typemap.KindTypeVar:
		return t.Name
	case typemap.KindList:
		return fmt.Sprintf("list[%s]", renderPyAnno(t.Params[0]))
	case typemap.KindSet:
		return fmt.Sprintf("set[%s]", renderPyAnno(t.Params[0]))
	case typemap.KindMap:
		return fmt.Sprintf("dict[%s, %s]", renderPyAnno(t.Params[0]), renderPyAnno(t.Params[1]))
	case typemap.KindTuple:
		var parts []string
		for _, p := range t.Params {
			parts = append(parts, renderPyAnno(p))
		}
		return fmt.Sprintf("Tuple[%s]", strings.Join(parts, ", "))
	case typemap.KindOptional:
		return fmt.Sprintf("Optional[%s]", renderPyAnno(t.Params[0]))
	case typemap.KindSum:
		var parts []string
		for _, p := range t.Params {
			parts = append(parts, renderPyAnno(p))
		}
		return fmt.Sprintf("Union[%s]", strings.Join(parts, ", "))
	case typemap.KindAsync:
		return fmt.Sprintf("Awaitable[%s]", renderPyAnno(t.Params[0]))
	case typemap.KindStream:
		return fmt.Sprintf("AsyncIterator[%s]", renderPyAnno(t.Params[0]))
	case typemap.KindFun:
		var parts []string
		for _, p := range t.FunParams() {
			parts = append(parts, renderPyAnno(p))
		}
		return fmt.Sprintf("Callable[[%s], %s]", strings.Join(parts, ", "), renderPyAnno(t.Return()))
	case typemap.KindRecord, typemap.KindInterface:
		return t.Name
	default:
		return "Any"
	}
}

func scalarPyAnno(name string) string {
	switch name {
	case "int":
		return "int"
	case "float":
		return "float"
	case "bool":
		return "bool"
	case "string":
		return "str"
	case "bytes":
		return "bytes"
	case "None":
		return "None"
	default:
		return name
	}
}

func paramSignature(params []typemap.MochiType) string {
	var parts []string
	for i := range params {
		parts = append(parts, fmt.Sprintf("arg%d", i))
	}
	return strings.Join(parts, ", ")
}

func lastDot(s string) string {
	i := strings.LastIndex(s, ".")
	if i < 0 {
		return s
	}
	return s[i+1:]
}

func isIteratorReturn(t typemap.MochiType) bool {
	// Phase 4 lowers Iterator[T] to list<T>; this companion is a hint for
	// future Phase 5 enhancement when we surface the lazy form separately.
	// We deliberately leave this off for the v1 wrapper to keep the surface
	// honest: the wrapper currently calls `_src.fn(...)` and lets the source
	// package's actual iterator come through unchanged.
	_ = t
	return false
}

func wrapperHelpers(w *Wrapper) []string {
	uses := map[string]bool{"_to_mochi_dict": true}
	if hasAsync(w) {
		uses["_run_async"] = true
		if w.Loop == EventLoopPersistent {
			uses["_persistent_loop"] = true
		}
	}
	for _, it := range w.Items {
		if it.Kind == ItemFunc && it.Type.Kind == typemap.KindFun {
			if isIteratorReturn(it.Type.Return()) {
				uses["_materialise_iter"] = true
			}
		}
	}
	names := make([]string, 0, len(uses))
	for n := range uses {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func hasAsync(w *Wrapper) bool {
	for _, it := range w.Items {
		if it.Kind == ItemFunc && it.IsAsync {
			return true
		}
	}
	return false
}

func needsAsyncio(w *Wrapper) bool {
	return hasAsync(w)
}
