package wrapper

// Runtime returns the shared `_mochi_wrap.py` helper module that ships
// alongside every <pkg>_externs.py wrapper. The file is emitted once per
// workspace at `<workdir>/python_wrap/_mochi_wrap.py`; all wrappers import
// the helpers it exposes through `from ._mochi_wrap import ...`.
//
// The runtime intentionally has no PyPI runtime dependencies and only uses
// the stdlib (asyncio, dataclasses, types). It is hand-written rather than
// synthesised because its surface is fixed by MEP-71 §7 and §6.
func Runtime() string {
	return runtimePY
}

// RuntimeStub returns the matching `_mochi_wrap.pyi`.
func RuntimeStub() string {
	return runtimePYI
}

const runtimePY = `# Auto-generated by mochi pkg lock — do not edit.
# MEP-71 wrapper runtime helpers. Shared by every <pkg>_externs.py.

from __future__ import annotations

import asyncio
import dataclasses
from typing import Any, Awaitable, Iterable, Iterator


def _run_async(awaitable: Awaitable[Any]) -> Any:
    """Per-call asyncio.run shim. Creates a fresh event loop per call.

    The wrapper's default async lowering. See MEP-71 §7.
    """
    return asyncio.run(awaitable)


_PERSISTENT_LOOP: asyncio.AbstractEventLoop | None = None


def _persistent_loop() -> asyncio.AbstractEventLoop:
    """Process-global asyncio event loop. Opt-in via mochi.toml
    [python] runtime = { event-loop = "persistent" }. The loop is created
    lazily on first call and reused for the lifetime of the process.
    """
    global _PERSISTENT_LOOP
    if _PERSISTENT_LOOP is None or _PERSISTENT_LOOP.is_closed():
        _PERSISTENT_LOOP = asyncio.new_event_loop()
    return _PERSISTENT_LOOP


def _materialise_iter(it: Iterable[Any]) -> list[Any]:
    """Eagerly materialise a Python iterator at the wrapper boundary so the
    Mochi side sees a concrete list. See MEP-71 §3 (Iterator[T] -> list<T>).
    """
    return list(it)


def _to_mochi_dict(value: Any) -> Any:
    """Convert a value to its Mochi record form.

    - dataclass instances -> dict via dataclasses.asdict (recursive).
    - TypedDict / dict pass through (dict is already record-shaped).
    - Sequences pass through (Mochi list lowering).
    - Scalars pass through.
    """
    if dataclasses.is_dataclass(value) and not isinstance(value, type):
        return dataclasses.asdict(value)
    return value
`

const runtimePYI = `# Auto-generated by mochi pkg lock — do not edit.
# MEP-71 wrapper runtime helper stubs.

from __future__ import annotations
from typing import Any, Awaitable, Iterable
import asyncio


def _run_async(awaitable: Awaitable[Any]) -> Any: ...


def _persistent_loop() -> asyncio.AbstractEventLoop: ...


def _materialise_iter(it: Iterable[Any]) -> list[Any]: ...


def _to_mochi_dict(value: Any) -> Any: ...
`
