package asyncbridge

import (
	"fmt"
	"strings"
)

// CrossLoopHelper is the Python source for the cross-loop hazard guard
// every shim invokes before driving the coroutine. The guard exists
// because `asyncio.run` and `loop.run_until_complete` both raise an
// opaque RuntimeError when a loop is already running on the current
// thread; we replace that with a clear MochiAsyncReentryError so the
// user sees the nesting hazard rather than an asyncio traceback.
const CrossLoopHelper = `class MochiAsyncReentryError(RuntimeError):
    """Raised when a sync shim is invoked from inside a running event loop.

    Driving a coroutine from inside the loop that owns it deadlocks the
    loop, so the bridge refuses the call. To call the async function
    from async code, await it directly instead of going through the
    _sync shim.
    """


def _mochi_check_no_running_loop(fn_name):
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return
    raise MochiAsyncReentryError(
        "cannot call %s from inside a running asyncio loop; await the async fn directly" % fn_name
    )
`

// PersistentLoopGetter is the Python source for the cached event loop
// the persistent mode reuses across shim calls. The cache is module-
// global on purpose: every shim shares the loop so that awaitables
// scheduled by one call can be observed by the next. The loop is never
// closed by the bridge — Python's interpreter shutdown finalises it.
const PersistentLoopGetter = `_MOCHI_LOOP = None


def _mochi_get_loop():
    global _MOCHI_LOOP
    if _MOCHI_LOOP is None or _MOCHI_LOOP.is_closed():
        _MOCHI_LOOP = asyncio.new_event_loop()
    return _MOCHI_LOOP
`

// RenderShim emits the synchronous shim source for one AsyncFn. The
// emitted function:
//
//  1. Calls _mochi_check_no_running_loop to convert the cross-loop
//     hazard into a clear error.
//  2. Drives the coroutine via asyncio.run (per-call) or
//     _mochi_get_loop().run_until_complete (persistent).
//
// RenderShim returns the shim source as a string with a trailing
// newline; it does not emit the `import asyncio` line — the caller is
// responsible for the surrounding module preamble (see Module.Render).
//
// RenderShim panics if the descriptor is invalid; callers should
// Validate up front.
func RenderShim(fn AsyncFn, mode Mode) string {
	if err := fn.Validate(); err != nil {
		panic(err)
	}
	params := make([]string, len(fn.ParamNames))
	for i, n := range fn.ParamNames {
		params[i] = fmt.Sprintf("%s: %s", n, fn.ParamTypes[i])
	}
	signature := strings.Join(params, ", ")
	args := strings.Join(fn.ParamNames, ", ")

	var driver string
	switch mode {
	case Persistent:
		driver = fmt.Sprintf("_mochi_get_loop().run_until_complete(%s(%s))", fn.Name, args)
	default:
		driver = fmt.Sprintf("asyncio.run(%s(%s))", fn.Name, args)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "def %s(%s) -> %s:\n", fn.SyncName, signature, fn.Return)
	fmt.Fprintf(&b, "    _mochi_check_no_running_loop(%q)\n", fn.SyncName)
	fmt.Fprintf(&b, "    return %s\n", driver)
	return b.String()
}

// Module is a renderable sync-shim Python module. SourceImport is the
// `from <pkg> import a, b, c` line that brings the async fns into
// scope; Fns lists the async fns in declaration order; Mode picks the
// loop strategy used by every shim in the module.
type Module struct {
	SourceImport string
	Fns          []AsyncFn
	Mode         Mode
}

// Render returns the complete module source: preamble (future import +
// asyncio import + source import) + cross-loop helper + (persistent loop
// getter if Persistent) + every shim. Output is deterministic given a
// fixed Fns order.
func (m Module) Render() (string, error) {
	for _, f := range m.Fns {
		if err := f.Validate(); err != nil {
			return "", err
		}
	}
	var b strings.Builder
	b.WriteString("# Generated by MEP-71 asyncbridge. Do not edit.\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("import asyncio\n")
	if strings.TrimSpace(m.SourceImport) != "" {
		b.WriteString(m.SourceImport)
		if !strings.HasSuffix(m.SourceImport, "\n") {
			b.WriteString("\n")
		}
	}
	b.WriteString("\n")
	b.WriteString(CrossLoopHelper)
	b.WriteString("\n")
	if m.Mode == Persistent {
		b.WriteString(PersistentLoopGetter)
		b.WriteString("\n")
	}
	for i, f := range m.Fns {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(RenderShim(f, m.Mode))
	}
	return b.String(), nil
}
