package uv

import (
	"strings"
	"testing"
)

// TestPhase2UvResolver is the gate sentinel for MEP-71 Phase 2. It exercises
// the round-trip that phase 9 (lockfile integration) will rely on: parse a
// uv.lock, convert to PEP 751, render, re-parse, and confirm structural
// equivalence.
func TestPhase2UvResolver(t *testing.T) {
	t.Run("parse_uv_lock", func(t *testing.T) {
		lf, err := ParseLockfile([]byte(sampleUvLock))
		if err != nil {
			t.Fatalf("ParseLockfile err = %v", err)
		}
		if lf.Version != 1 {
			t.Errorf("Version = %d; want 1", lf.Version)
		}
		if len(lf.Packages) != 4 {
			t.Errorf("packages = %d; want 4", len(lf.Packages))
		}
	})

	t.Run("uv_lock_to_pylock", func(t *testing.T) {
		lf, _ := ParseLockfile([]byte(sampleUvLock))
		pl := FromLockfile(lf)
		out := pl.Render()
		// Sanity: the bridge identifies itself, the canonical lock-version is "1.0".
		if !strings.HasPrefix(out, "# Generated by mochi-python-bridge") {
			t.Error("missing canonical header")
		}
		if !strings.Contains(out, `lock-version = "1.0"`) {
			t.Error("missing lock-version 1.0")
		}
		if !strings.Contains(out, `created-by = "mochi-python-bridge"`) {
			t.Error("missing created-by")
		}
	})

	t.Run("pylock_round_trip", func(t *testing.T) {
		pl, err := ParsePyLock([]byte(samplePyLock))
		if err != nil {
			t.Fatalf("ParsePyLock err = %v", err)
		}
		out := pl.Render()
		pl2, err := ParsePyLock([]byte(out))
		if err != nil {
			t.Fatalf("re-parse err = %v", err)
		}
		if len(pl.Packages) != len(pl2.Packages) {
			t.Errorf("count mismatch: %d -> %d", len(pl.Packages), len(pl2.Packages))
		}
	})

	t.Run("runner_options", func(t *testing.T) {
		opts := LockOptions{
			PythonVersion:  "3.13",
			Resolution:     "lowest-direct",
			IndexURL:       "https://pypi.org/simple",
			ExtraIndexURLs: []string{"https://internal/simple"},
			NoBuild:        true,
		}
		args := opts.BuildLockArgs()
		expectArg(t, args, "--python")
		expectArg(t, args, "3.13")
		expectArg(t, args, "--resolution")
		expectArg(t, args, "lowest-direct")
		expectArg(t, args, "--index-url")
		expectArg(t, args, "--extra-index-url")
		expectArg(t, args, "--no-build")
	})

	t.Run("md5_split_hash_rejected", func(t *testing.T) {
		// Phase 1 hardened against md5; the SplitHash helper does not itself
		// gate algorithms (callers do), but it must surface algo+hex
		// faithfully so callers can refuse based on the algo string.
		algo, _, ok := SplitHash("md5:abcdef")
		if !ok {
			t.Fatal("SplitHash returned ok=false")
		}
		if algo != "md5" {
			t.Errorf("algo = %q; want md5", algo)
		}
	})
}

func expectArg(t *testing.T, args []string, want string) {
	t.Helper()
	for _, a := range args {
		if a == want {
			return
		}
	}
	t.Errorf("missing arg %q in %q", want, args)
}
