package uv

import (
	"strings"
	"testing"
)

const samplePyLock = `lock-version = "1.0"
created-by = "uv"
requires-python = ">=3.10"

[[packages]]
name = "httpx"
version = "0.27.0"
requires-python = ">=3.8"
dependencies = ["anyio", "certifi"]

[[packages.wheels]]
name = "httpx-0.27.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/abc/httpx-0.27.0-py3-none-any.whl"
hashes = {sha256 = "cafebabe"}

[packages.sdist]
name = "httpx-0.27.0.tar.gz"
url = "https://files.pythonhosted.org/packages/xyz/httpx-0.27.0.tar.gz"
hashes = {sha256 = "deadbeef"}

[[packages]]
name = "anyio"
version = "4.3.0"
marker = "python_version >= '3.10'"

[[packages.wheels]]
name = "anyio-4.3.0-py3-none-any.whl"
url = "https://example.com/anyio-4.3.0-py3-none-any.whl"
hashes = {sha256 = "feedface", blake3 = "abc123"}
`

func TestParsePyLock(t *testing.T) {
	pl, err := ParsePyLock([]byte(samplePyLock))
	if err != nil {
		t.Fatalf("ParsePyLock err = %v", err)
	}
	if pl.LockVersion != "1.0" {
		t.Errorf("LockVersion = %q", pl.LockVersion)
	}
	if pl.CreatedBy != "uv" {
		t.Errorf("CreatedBy = %q", pl.CreatedBy)
	}
	if pl.RequiresPython != ">=3.10" {
		t.Errorf("RequiresPython = %q", pl.RequiresPython)
	}
	if len(pl.Packages) != 2 {
		t.Fatalf("len(Packages) = %d", len(pl.Packages))
	}
	httpx := pl.Packages[0]
	if httpx.Name != "httpx" || httpx.Version != "0.27.0" {
		t.Errorf("httpx = %+v", httpx)
	}
	if len(httpx.Dependencies) != 2 {
		t.Errorf("httpx deps = %v", httpx.Dependencies)
	}
	if len(httpx.Wheels) != 1 || httpx.Wheels[0].Hashes["sha256"] != "cafebabe" {
		t.Errorf("httpx wheels = %+v", httpx.Wheels)
	}
	if httpx.Sdist == nil || httpx.Sdist.Hashes["sha256"] != "deadbeef" {
		t.Errorf("httpx sdist = %+v", httpx.Sdist)
	}

	anyio := pl.Packages[1]
	if anyio.Marker == "" {
		t.Errorf("anyio marker = %q; want non-empty", anyio.Marker)
	}
	if anyio.Wheels[0].Hashes["blake3"] != "abc123" {
		t.Errorf("anyio blake3 = %q", anyio.Wheels[0].Hashes["blake3"])
	}
}

func TestParsePyLockMissingHashes(t *testing.T) {
	src := `lock-version = "1.0"
[[packages]]
name = "x"
version = "1.0"

[[packages.wheels]]
name = "x-1.whl"
url = "https://example.com/x-1.whl"
`
	_, err := ParsePyLock([]byte(src))
	if err == nil {
		t.Fatal("ParsePyLock err = nil; want missing hashes error")
	}
}

func TestRenderPyLockRoundTrip(t *testing.T) {
	pl, err := ParsePyLock([]byte(samplePyLock))
	if err != nil {
		t.Fatalf("ParsePyLock err = %v", err)
	}
	out := pl.Render()

	pl2, err := ParsePyLock([]byte(out))
	if err != nil {
		t.Fatalf("re-parse err = %v", err)
	}
	if len(pl2.Packages) != len(pl.Packages) {
		t.Errorf("re-parsed packages count = %d; want %d", len(pl2.Packages), len(pl.Packages))
	}
	// Order should be by name: anyio before httpx.
	if pl2.Packages[0].Name != "anyio" || pl2.Packages[1].Name != "httpx" {
		t.Errorf("re-parsed order = %q, %q; want anyio, httpx", pl2.Packages[0].Name, pl2.Packages[1].Name)
	}
}

func TestRenderPyLockDeterministic(t *testing.T) {
	pl, _ := ParsePyLock([]byte(samplePyLock))
	first := pl.Render()
	for i := 0; i < 5; i++ {
		if got := pl.Render(); got != first {
			t.Fatalf("Render not deterministic on iteration %d", i)
		}
	}
}

func TestRenderPyLockContainsCanonicalHeader(t *testing.T) {
	pl, _ := ParsePyLock([]byte(samplePyLock))
	out := pl.Render()
	if !strings.HasPrefix(out, "# Generated by mochi-python-bridge") {
		t.Errorf("Render does not start with the canonical header. Got: %s", out[:40])
	}
	if !strings.Contains(out, `lock-version = "1.0"`) {
		t.Errorf("missing lock-version: %s", out)
	}
	if !strings.Contains(out, `created-by = "uv"`) {
		t.Errorf("missing created-by: %s", out)
	}
}

func TestRenderPyLockHashesSorted(t *testing.T) {
	pl, _ := ParsePyLock([]byte(samplePyLock))
	out := pl.Render()
	// anyio has both blake3 and sha256; rendered order must be alphabetical.
	idx := strings.Index(out, "anyio-4.3.0-py3-none-any.whl")
	if idx < 0 {
		t.Fatal("anyio wheel missing from render")
	}
	section := out[idx:]
	bIdx := strings.Index(section, "blake3")
	sIdx := strings.Index(section, "sha256")
	if bIdx == -1 || sIdx == -1 || bIdx > sIdx {
		t.Errorf("hashes not sorted: blake3@%d sha256@%d", bIdx, sIdx)
	}
}

func TestFromLockfile(t *testing.T) {
	lf, _ := ParseLockfile([]byte(sampleUvLock))
	pl := FromLockfile(lf)
	if pl.LockVersion != "1.0" || pl.CreatedBy != "mochi-python-bridge" {
		t.Errorf("envelope = %+v", pl)
	}
	if pl.RequiresPython != ">=3.10" {
		t.Errorf("requires-python = %q", pl.RequiresPython)
	}
	if len(pl.Packages) != 4 {
		t.Fatalf("packages = %d; want 4", len(pl.Packages))
	}
	httpx := pl.Packages[0]
	if httpx.Name != "httpx" {
		t.Errorf("httpx first = %q", httpx.Name)
	}
	if len(httpx.Wheels) != 2 {
		t.Errorf("len(wheels) = %d", len(httpx.Wheels))
	}
	if httpx.Wheels[0].Hashes["sha256"] == "" {
		t.Errorf("missing sha256 on wheel: %+v", httpx.Wheels[0])
	}
	if httpx.Sdist == nil {
		t.Error("httpx.sdist = nil")
	}
	// Filename should have been derived from the URL.
	if httpx.Wheels[0].Name == "" {
		t.Errorf("wheel name not derived; got empty")
	}
	if !strings.HasSuffix(httpx.Wheels[0].Name, ".whl") {
		t.Errorf("wheel name = %q; want .whl suffix", httpx.Wheels[0].Name)
	}
}

func TestFromLockfileRoundTripPyLock(t *testing.T) {
	lf, _ := ParseLockfile([]byte(sampleUvLock))
	pl := FromLockfile(lf)
	out := pl.Render()
	pl2, err := ParsePyLock([]byte(out))
	if err != nil {
		t.Fatalf("re-parse err = %v", err)
	}
	if len(pl2.Packages) != len(pl.Packages) {
		t.Errorf("count after round-trip = %d; want %d", len(pl2.Packages), len(pl.Packages))
	}
}
